### ISSUE TITLE
speech prompt V2

### ISSUE THREAD

**Issue by xiaoxue1117** [ga642381/SpeechPrompt#5]
Hi, congratulations on your great work of speech prompt and its version2. I am very interested in the speech prompt V2. May I have access to your codes of speech prompt v2? Thank you in advance!

**Comment by ga642381** [comment]
Hi, @xiaoxue1117. Thank you! I will release the code of SpeechPrompt v2 (prompt tuning for various speech classification tasks) in these two days. The code is refactored, and the document is more complete. I'll come back here when the code is released. Thanks for your patience in advance :)

**Comment by ga642381** [comment]
The source code of SpeechPrompt v2 has been released on https://github.com/ga642381/SpeechPrompt-v2 :smiley:

**Comment by xiaoxue1117** [comment]
Thank you for your reply! Great work!
